// Create Redux action types
const CLEAR_PLAYLIST = 'CLEAR_PLAYLIST';
const SEARCH_VIDEO = 'SEARCH_VIDEO';
const SEARCH_VIDEO_SUCCESS = 'SEARCH_VIDEO_SUCCESS';
const SEARCH_VIDEO_FAILURE = 'SEARCH_VIDEO_FAILURE';

export {
  CLEAR_PLAYLIST,
  SEARCH_VIDEO,
  SEARCH_VIDEO_SUCCESS,
  SEARCH_VIDEO_FAILURE,
};
