export enum ActionTypes {
  CLEAR_PLAYLIST = 'CLEAR_PLAYLIST',
  FETCH_POPULAR_VIDEO = 'FETCH_POPULAR_VIDEO',
  FETCH_POPULAR_VIDEO_SUCCESS = 'FETCH_POPULAR_VIDEO_SUCCESS',
  FETCH_POPULAR_VIDEO_FAILURE = 'FETCH_POPULAR_VIDEO_FAILURE',
  SEARCH_VIDEO = 'SEARCH_VIDEO',
  SEARCH_VIDEO_SUCCESS = 'SEARCH_VIDEO_SUCCESS',
  SEARCH_VIDEO_FAILURE = 'SEARCH_VIDEO_FAILURE',
};
