// Create Redux action types
const CLEAR_PLAYLIST = 'CLEAR_PLAYLIST';
const FETCH_POPULAR_VIDEO = 'FETCH_POPULAR_VIDEO';
const FETCH_POPULAR_VIDEO_SUCCESS = 'FETCH_POPULAR_VIDEO_SUCCESS';
const FETCH_POPULAR_VIDEO_FAILURE = 'FETCH_POPULAR_VIDEO_FAILURE';
const SEARCH_VIDEO = 'SEARCH_VIDEO';
const SEARCH_VIDEO_SUCCESS = 'SEARCH_VIDEO_SUCCESS';
const SEARCH_VIDEO_FAILURE = 'SEARCH_VIDEO_FAILURE';

export {
  CLEAR_PLAYLIST,
  FETCH_POPULAR_VIDEO,
  FETCH_POPULAR_VIDEO_SUCCESS,
  FETCH_POPULAR_VIDEO_FAILURE,
  SEARCH_VIDEO,
  SEARCH_VIDEO_SUCCESS,
  SEARCH_VIDEO_FAILURE,
};
