export enum ActionTypes {
  GET_OVERVIEW_DETAIL = 'GET_OVERVIEW_DETAIL',
  GET_OVERVIEW_DETAIL_SUCCESS = 'GET_OVERVIEW_DETAIL_SUCCESS',
  GET_OVERVIEW_DETAIL_FAILURE = 'GET_OVERVIEW_DETAIL_FAILURE',
}
