const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
const GET_ALL_EVENTS_SUCCESS = 'GET_ALL_EVENTS_SUCCESS';
const GET_ALL_EVENTS_FAILURE = 'GET_ALL_EVENTS_FAILURE';

export {
  GET_ALL_EVENTS,
  GET_ALL_EVENTS_SUCCESS,
  GET_ALL_EVENTS_FAILURE,
};
