name: repo/check
on:
  pull_request:
    branches:
      - main
      - master
defaults:
  run:
    working-directory: src
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
      - name: Check lint
        run: npx eslint .
      - name: Check type
        run: npx tsc -p tsconfig.json
